### ISSUE TITLE
Add to readme that it requires 64 bit host

### ISSUE THREAD

**Issue by darius-v** [1and1internet/ubuntu-16-apache-php-7.2#1]
I have 32 bit ubuntu and it turns out that it does not support this image.

Users would save time if this was in readme.md.

https://stackoverflow.com/questions/48174393/running-docker-1-13-1-container-as-daemon-and-telling-to-wait-for-interactive-in

**Comment by hrobertson** [comment]
Thank you for your comment.

As Docker itself requires a 64-bit host, we will not be amending the readme.

Running Docker on a 32-bit host is not officially supported and my understanding is that it requires using a custom build of Docker. The default expectation, therefore, should be that images require a 64-bit host unless stated otherwise, rather than the opposite.

Further reading: https://github.com/moby/moby/issues/136

I wish you well with your containerisation endeavours.
